/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SavedTrip = IDL.Record({
  'id' : IDL.Text,
  'destination' : IDL.Text,
  'cabinClass' : IDL.Text,
  'tripType' : IDL.Text,
  'departureDate' : IDL.Text,
  'origin' : IDL.Text,
  'passengers' : IDL.Nat,
  'savedAt' : IDL.Int,
  'providerName' : IDL.Text,
  'price' : IDL.Text,
  'returnDate' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteTrip' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSavedTrips' : IDL.Func([], [IDL.Vec(SavedTrip)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveTrip' : IDL.Func([SavedTrip], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SavedTrip = IDL.Record({
    'id' : IDL.Text,
    'destination' : IDL.Text,
    'cabinClass' : IDL.Text,
    'tripType' : IDL.Text,
    'departureDate' : IDL.Text,
    'origin' : IDL.Text,
    'passengers' : IDL.Nat,
    'savedAt' : IDL.Int,
    'providerName' : IDL.Text,
    'price' : IDL.Text,
    'returnDate' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteTrip' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSavedTrips' : IDL.Func([], [IDL.Vec(SavedTrip)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveTrip' : IDL.Func([SavedTrip], [], []),
  });
};

export const init = ({ IDL }) => { return []; };